variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

jobs:
  - job: Windows
    pool:
      vmImage: windows-latest
    strategy:
      maxParallel: 3
      matrix:
        node-10:
          node_version: ^10.13.0
        node-12:
          node_version: ^12.4.0
        node-16:
          node_version: ^16.0.0
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: "Install Node.js $(node_version)"
      - script: |
          npm install --global yarn
        displayName: "Install Yarn"
      - script: |
          node -v
          yarn -v
        displayName: "Print versions"
      - task: CacheBeta@1
        inputs:
          key: yarn | $(Agent.OS) | yarn.lock
          path: $(YARN_CACHE_FOLDER)
        displayName: "Cache Yarn packages"
      - script: yarn --frozen-lockfile
        displayName: "Install dependencies"
      - script: yarn link --frozen-lockfile || true
        displayName: "Link webpack"
        continueOnError: true
      - script: yarn link webpack --frozen-lockfile
        displayName: "Link webpack into node_modules"
      - script: |
          yarn cover:integration --ci --maxWorkers=2 --reporters=default --reporters=jest-junit ConfigCacheTestCases
          yarn cover:merge
        env:
          CI: "true"
          DEBUG_INFO: "true"
        displayName: "Run tests with coverage"
      - task: PublishTestResults@2
        inputs:
          testRunTitle: "Windows with Node.js $(node_version)"
          testResultsFiles: "**/junit.xml"
        condition: succeededOrFailed()
        displayName: "Publish test results"
